### ISSUE TITLE
report sequence database stats

### ISSUE THREAD

**Issue by alexmasselot** [vitalit-sib/msviz-backend#16]
sequence source, number of entries
if possible fast, number of residues

**Comment by TrinidadMartin** [comment]
I tested into mongo and I got this:

[ { "source" : null, "nbEntries" : 2, "nbResidues" : 694 } ]

So, without the source we obtain same results:

[ { "nbEntries" : 2, "nbResidues" : 694 } ]

Could we just remove the source???

Abd for the reduce:function...do you have an example about how to translate into BSONDocument??

**Comment by alexmasselot** [comment]
http://localhost:9000/sequence/stats
