### ISSUE TITLE
Unimod export

### ISSUE THREAD

**Issue by TrinidadMartin** [vitalit-sib/msviz-backend#28]
Extract:

- key
- delta mass
- monoisotopic mass
- description

**Comment by rmylonas** [comment]
We should try to get it from our local Mascot server.
If not possible we'll grab it from the public Unimod server.

**Comment by TrinidadMartin** [comment]
- Unimod.xml got from our local Mascot server done!!
- key, delta mass and mono isotopic mass done!!
- description, should we use directly the url like http://www.ionsource.com/Card/acetylation/acetylation.htm??

**Comment by TrinidadMartin** [comment]
Dictionary finished with:

Map(modificationName, mono_mass): (String,String)
